alias mv='mv -i'
alias cp='cp -i'
alias ll='ls -lahF --color=auto'
alias ls='ls -F --color=auto'
alias cls='clear'
alias grep='grep --color=auto'

alias ff='fastfetch'
alias eza='eza --long --all --header --inode'
alias zshrc='nvim ~/.zshrc'
alias zshenv='nvim ~/.config/zsh/functions/env.zsh'
