#!/bin/bash

# Require nbfc-linux(yay)

########################## Functions #######################

# Load the ec_sys module with write support
ec_write_support() {
  modprobe ec_sys write_support=$1
}

change_mode() {
  case "$1" in
  "bios")
    printf '\x00' | dd of=/sys/kernel/debug/ec/ec0/io bs=1 seek=$((0x15)) count=1 conv=notrunc
    printf '\xff' | dd of=/sys/kernel/debug/ec/ec0/io bs=1 seek=$((0x19)) count=1 conv=notrunc
    echo "Switch to BIOS controlled mode."
    ;;
  "user")
    printf '\x01' | dd of=/sys/kernel/debug/ec/ec0/io bs=1 seek=$((0x15)) count=1 conv=notrunc
    echo "Switch to USER controlled mode."
    ;;
  *)
    echo "Error: No such mode!"
    exit 1
    ;;
  esac
}

change_speed() {
  printf $(printf '\\x%x' $1) | dd of=/sys/kernel/debug/ec/ec0/io bs=1 seek=$((0x19)) count=1 conv=notrunc
  ec_probe read 0x19
}

############################# Body ###########################

# Check if you are root
if [ $(whoami) != "root" ]; then
  echo "ERROR: This script must be run as root"
  exit 1
fi

# Check arguments
if [[ $# -ne 2 ]]; then
  echo "Usage: omenfan mode  <mode>"
  echo "       omenfan speed <speed>"
  exit 1
fi

ec_write_support 1

# Get subcommand and argument
subcommand=$1
argument=$2

# Do job
case "$subcommand" in
"mode")
  change_mode $argument
  ;;
"speed")
  change_speed $argument
  ;;
*)
  echo "No such subcommand!"
  ;;
esac
